import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ThemePrivider from "@/providers/ThemeProvider";
import NextUI from "@/providers/NextUI";
import Navigation from "@/components/Navigation";
import Session from "@/services/session";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const hasSession = Session().get();

  return (
    <html lang="en" className="light">
      <body className={inter.className}>
        <ThemePrivider>
          <NextUI>
            <Navigation hasSession={hasSession} />
            <main className="container pt-5 text-center">{children}</main>
          </NextUI>
        </ThemePrivider>
      </body>
    </html>
  );
}
